package Emus;

import javax.swing.JOptionPane;

import MyMatch.EmusDeff;
import MyMatch.MyMatch;
import MyMatch.Setings;

/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. */
/**
 *
 * @author Terran
 */
public class ORION extends EmusDeff {

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem				InstalZero;

	private javax.swing.JMenuItem				Reset;

	private javax.swing.JMenu					jMenu2;

	private javax.swing.JMenu					jMenu4;

	private javax.swing.JMenuItem				jMenuItem1;

	private javax.swing.JMenuItem				jMenuItem2;

	private javax.swing.JMenuItem				jMenuItem3;

	private javax.swing.JRadioButtonMenuItem	jMenuItem4;

	private javax.swing.JMenuItem				jMenuItem5;

	private javax.swing.JRadioButtonMenuItem	jMenuItem6;
	private boolean								isRandom	= false;
	private boolean								isErr		= false;

	// End of variables declaration//GEN-END:variables

	public ORION(Setings aThis) {
		super(aThis, "ORION", 1000);
	}

	@Override
	protected void firstStep() {
		TextList.removeAll();
		TextList.add("Error");
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		String res = JOptionPane.showInputDialog(this, "Введите код, который надо пустить");
		if (res == null) { return; }

		numKontr = Integer.parseInt(res);
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
		isRandom = !isRandom;
		jMenuItem4.setSelected(isRandom);
	}// GEN-LAST:event_jMenuItem4ActionPerformed

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem6ActionPerformed
		isErr = !isErr;
		jMenuItem6.setSelected(isErr);
	}// GEN-LAST:event_jMenuItem6ActionPerformed

	@Override
	protected void msgIn(String data_S, String string_H) {

		println("In" + string_H);

		String req[] = string_H.split(" ");
		int num = Integer.parseInt(req[0]);
		int fun = Integer.parseInt(req[1]);
		println("Адрес = " + num + " Функция = " + fun);

		byte[] array1;
		if (isErr) {
			array1 = new byte[] { 0, 1, 2, 3, 4 };
			array1[0] = (byte) num;
			array1[1] = (byte) (fun | 0x80);
			array1[2] = (byte) (1 + Math.random() * 15); // код ошибки

			int[] crc = MyMatch.calculateCRC(array1, 0, array1.length - 2);
			array1[array1.length - 2] = (byte) crc[0]; // CRC
			array1[array1.length - 1] = (byte) crc[1];
		} else {
			array1 = new byte[] { 0, 1, 2, 3, 4, 5, 6 };
			array1[0] = (byte) num;
			array1[1] = (byte) fun;
			array1[2] = (byte) 2; // счётчик байт полезного сообщения

			array1[3] = (byte) numKontr;
			numKontr = 0;
			array1[4] = (byte) 0;

			int[] crc = MyMatch.calculateCRC(array1, 0, array1.length - 2);
			array1[array1.length - 2] = (byte) crc[0]; // CRC
			array1[array1.length - 1] = (byte) crc[1];
		}
		writeBytes(array1);
		String data = "";
		for (byte element : array1) {
			data += " " + String.format("%02X ", element);
		}
		println("Out" + data);

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	@Override
	protected void newInitComponents() {

		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem4 = new javax.swing.JRadioButtonMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JRadioButtonMenuItem();
		Reset = new javax.swing.JMenuItem();
		InstalZero = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jMenuItem1.setText("Устновить значение");
		jMenuItem1.addActionListener(evt -> jMenuItem1ActionPerformed(evt));
		Menu.add(jMenuItem1);

		jMenuItem4.setText("Случайные");
		jMenuItem4.setSelected(false);
		jMenuItem4.addActionListener(evt -> jMenuItem4ActionPerformed(evt));
		Menu.add(jMenuItem4);

		jMenuItem6.setText("Отказ");
		jMenuItem6.setSelected(false);
		jMenuItem6.addActionListener(evt -> jMenuItem6ActionPerformed(evt));
		Menu.add(jMenuItem6);

		setTitle("Эмулятор охранно-пожарной системы ОРИОН");

	}// </editor-fold>//GEN-END:initComponents

	@Override
	protected void newStep() {
		if (isRandom) {
			numKontr = (int) (Math.random() * 127);
		}
		TextList.removeAll();
		if (isErr) {
			TextList.add("Error");
		} else {
			TextList.add(numKontr + "");
		}
	}

	@Override
	protected Controller getController(int numContr, int numPart) {
		return null;
	}
}
