package Emus;

import javax.swing.JOptionPane;

import MyMatch.EmusDeff;
import MyMatch.MyMatch;
import MyMatch.Setings;

/* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. */
/**
 *
 * @author Terran
 */
public class ZTE extends EmusDeff {

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private boolean								isErr		= false;

	// End of variables declaration//GEN-END:variables

	public ZTE(Setings aThis) {
		super(aThis, "ZTE", 1000);
	}

	@Override
	protected void firstStep() {
		TextList.removeAll();
		TextList.add("Error");
	}

	@Override
	protected void msgIn(String data_S, String string_H) {
		data_S = data_S.replaceAll("\r", "");
		println("In " + data_S);
		if(data_S.contains("ATDT"))
			writeString(data_S + "\r\nCONNECT\r\n");
		else if(!data_S.isEmpty())
			writeString(data_S + "\r\nok\r\n");
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	@Override
	protected void newInitComponents() {
		setTitle("Модем от ZTE");

	}// </editor-fold>//GEN-END:initComponents

	@Override
	protected void newStep() {}

	@Override
	protected Controller getController(int numContr, int numPart) {
		return null;
	}
}
